fit content-sample
Phizick/Liza-project pull request #25
Opened 2022-05-20 20:09 UTC by AlekseyShaydullin

Добавил шаблон под блок content

2022-05-20 20:23 UTC, SergeyNerusin requested changes

2022-05-20 20:23 UTC, SergeyNerusin commented on pages/index.css
> +@import url('../blocks/content-block//__title/content-block__title.css');
@import url('../blocks/content-block//__title/content-block__title.css');
Задвоен слэш - нужно проверить путь...

2022-05-21 07:06 UTC, SergeyNerusin approved these changes
Привет, Ок.

2022-05-21 10:37 UTC, burlackoff commented on index.html
> +      <div class="content-block__two-columns"></div>
Для чего нужен этот блок?

2022-05-21 10:42 UTC, burlackoff commented on index.html
> +    <section class="content-block">
Блока занимает всю высоту экрана, возможно нужна дополнительная обертка.

2022-05-21 10:43 UTC, burlackoff reviewed
Есть вопросы к разметке, посмотри

2022-05-21 13:29 UTC, Phizick commented
переделать

2022-05-21 13:29 UTC, closed without merging