refactor: переименование блока на result страниц тест пройден/не пройден
Phizick/Liza-project pull request #44
Opened 2022-05-22 21:09 UTC by SergeyNerusin

полный рефакторинг блока result  для возможного переиспользования.

2022-05-22 21:24 UTC, burlackoff reviewed
Поправить блок result

2022-05-22 21:24 UTC, burlackoff commented on blocks/result/_padding/result_padding-little.css
> +@media(max-width:430px) {
Перенести медиазапрос в блок result

2022-05-22 21:24 UTC, burlackoff commented on pages/testCompleetLoss.css
> +@import url('../blocks/result/_padding/result_padding-little.css');
Удалить

2022-05-22 21:24 UTC, burlackoff commented on pages/testCompleetWin.css
> +@import url('../blocks/result/_padding/result_padding-little.css');
Удалить

2022-05-22 21:24 UTC, burlackoff commented on testCompleetWin.html
> +          <div class="result result_padding-little">
Оставить только блок result

2022-05-22 21:24 UTC, burlackoff commented on testCompletedLoss.html
> +          <div class="result result_padding-little">
Оставить только блок result

2022-05-23 09:07 UTC, Phizick approved these changes

2022-05-23 10:48 UTC, burlackoff requested changes
Исправить коменты

2022-05-23 15:27 UTC, merged